name: Docker
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.editorconfig'
      - 'examples/**'
      - '.jenkins'
      - '.jenkins.d/**'
      - '.mailmap'
      - 'tests/**'
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  ndn-cxx-build:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndn-cxx-build
      target: build
  ndn-cxx-runtime:
    needs: ndn-cxx-build
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: ndn-cxx-runtime
      target: runtime
      contexts: build=docker-image://${{ needs.ndn-cxx-build.outputs.image }}
