name: Release
on:
  push:
    tags:
      - 'ndn-cxx-[0-9]+*'
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
